[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
    bblanchon/ArduinoJson
    marcoschwartz/LiquidCrystal_I2C
build_flags =
    -D CONFIG_FREERTOS_HZ=1000
    -D ARDUINO_LOOP_STACK_SIZE=8192